apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3  # Adjust the number of replicas as needed for your application
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: petegichana/yolo-backend:1.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: <your-mongo-db-uri>
