apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
  labels:
    app: yolo-client
spec:
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: yolo-client
          image: petegichana/yolo-client:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: yolo-client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 32000