version: "3.8"
services:
  client:
    image: yolo-client:1.0
    ports:
      - 3000:3000 
    depends_on:
      - backend  

  backend:
    image: yolo-backend:1.0
    ports:
      - 5000:5000
    environment:
      DB_URL: mongodb+srv://petegichana:2011417242.Ab@yolomy.zuy3bjh.mongodb.net/  
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - /path/to/mongo_data:/data/db


