version: "3.8"
services:
  client:
    image: petegichana/yolo-client:1.0
    ports:
      - 3000:3000 
    depends_on:
      - backend  
  backend:
    image: petegichana/yolo-backend:1.0
    ports:
      - 5000:5000